import Navbar from "./component/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto p-4">
          <div className="text-center">
            <h1 className="text-5xl font-extrabold text-gray-700 mb-4">
              CRUD APP 
            </h1>
            <div className="w-20 h-1 bg-gray-700 mx-auto mb-8"></div>
          </div>
          <Navbar />
          <div className="mt-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
